"""first try

Revision ID: 489741f24683
Revises: 
Create Date: 2023-08-02 21:02:04.312446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489741f24683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
